---
title: "My Map"
author: ""
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: html_document
---

```{r setup, include=FALSE}
if (TRUE) {
  list.of.packages <- c("tidyverse", "haven", "here", "kableExtra","rstudioapi",
                        "DescTools","qwraps2","data.table","stargazer","readxl","dplyr",
                        "rootSolve","sp","raster","rgdal","leaflet","wesanderson","plotKML",
                        "mapview")
  new.packages <- list.of.packages[
    !( list.of.packages %in% installed.packages()[,"Package"] )
  ]
  if(length(new.packages)) install.packages(new.packages,
                                            repos = "https://cloud.r-project.org")
  
  lapply(list.of.packages, library, character.only = TRUE)
}

setwd(dirname(getActiveDocumentContext()$path)) 

knitr::opts_knit$set(root.dir = here())
knitr::opts_chunk$set(echo = T, eval = T, message = F, warning = F, fig.pos = "H", fig.height = 6, fig.width = 12)

```

# Map in Leaflet


```{r, include=FALSE}
# Get map data
basemap <- leaflet() %>% addProviderTiles("CartoDB.Positron")
wldmap <- rgdal::readOGR(dsn = "./World_Countries__Generalized_", layer = "World_Countries__Generalized_", encoding = "UTF-8") # downloaded Esri ArcGIS Hub (https://hub.arcgis.com/datasets/esri::world-countries-generalized/about)

# Remove Antarctica
wldmap <- wldmap[wldmap@data$ISO!="AQ",]

## Countries where I have had professional relationships
biz_country <- c("AU","BD","BF","CA","CL","CN","CY","DE","EG","FR","GB",
                 "IL","IN","KE","KH","KR","LK","MN","MX","NG","PL","RU",
                 "SG","US")

## Countries I visited
vis_country <- c("AU","BE","BN","CA","FR","GB","GU","IN","IT","KE",
                 "KH","KR","MX","NL","NZ","PH","SG","TH","TW","US","VN")

## Countries my friends come from
fri_country <- c("AE","AF","AL","AU","BN","BR","CN","CO","CV","DK","ES",
                 "FR","HK","IN","IT","KE","KP","KR","MM","MX","PE","PH",
                 "PK","PR","SA","SV","TH","TW","UG","US","USA","VN")

# Subset countries
biz <- wldmap[wldmap@data$ISO %in% biz_country,]
vis <- wldmap[wldmap@data$ISO %in% vis_country,]
fri <- wldmap[wldmap@data$ISO %in% fri_country,]
hom <- wldmap[wldmap@data$ISO == "JP",]
```

Show a map

```{r}
basemap %>%
  # Home - Black
  # Friends - Red
  # Business - Blue
  # Visit - Orange
  addPolygons(data=hom, color = "black",
              weight = 1, fillOpacity = 0.3,
              group = "Home",
              popup = paste("<p>", hom@data$COUNTRY,"<p>")) %>%
  addPolygons(data=biz, color = "blue",
              weight = 1, fillOpacity = 0.3,
              group = "Business",
              popup = paste("<p>", biz@data$COUNTRY,"<p>")) %>%
  addPolygons(data=vis, color = "orange",
              weight = 1, fillOpacity = 0.3,
              group = "Visited",
              popup = paste("<p>", vis@data$COUNTRY,"<p>")) %>%
  addPolygons(data=fri, color = "red",
              weight = 1, fillOpacity = 0.3,
              group = "Friends",
              popup = paste("<p>", fri@data$COUNTRY,"<p>")) %>%
  addLayersControl(overlayGroups = c("Friends","Visited","Business"))
  
```


# Map in ggplot

```{r}
# Loading World data
world <- map_data("world")

world$region %>% 
  unique()

biz_country <- c("Australia","Bangladesh","Burkina Faso",
                 "Chile","Cyprus","China","Germany","Egypt","France",
                 "UK","India","Israel","Italy","Kenya","Cambodia","South Korea",
                 "Sri Lanka","Mongolia","Poland","Russia","Singapore","USA")
vis_country <- c("Australia","Belgium","Brunei","Canada","France",
                 "Guam","India","Italy","Kenya","Cambodia","South Korea",
                 "Mexico","Netherlands","New Zealand","Philippines","Singapore",
                 "Thailand","Taiwan","USA","Vietnam")
fri_country <- c("Afghanistan","Albania","Australia","Brazil","Brunei",
                 "Canada","Colombia","Cape Verde","China","Denmark","Spain",
                 "France","India","Italy","Kenya",
                 "South Korea","Saudi Arabia","Mexico","Myanmar",
                 "Pakistan","Peru","Philippines","Puerto Rico",
                 "North Korea","El Salvador","Thailand","Taiwan","Uganda",
                 "USA","United Arab Emirates","Vietnam")


# Remove the Antarctica region
world <- subset(world, region != "Antarctica")
# Remove the French Southern and Antarctic Lands region
world <- subset(world, region != "French Southern and Antarctic Lands")

world$cat <- NA
world$cat[world$region %in% biz_country] <- "biz"
world$cat[world$region %in% fri_country] <- "fri"
world$cat[world$region %in% vis_country] <- "vis"
world$cat[world$region %in% c("Japan")] <- "hom"
world$cat <- replace_na(world$cat,'NA')

world$cat <- factor(world$cat, levels = c("biz","fri","vis","hom","NA"))

```

Show a map

```{r}
# plot
ggplot(data = world, aes(x = long, y = lat, group = group)) + 
  geom_polygon(fill = "white", color = "black", size = 0.3) +
  geom_polygon(aes(fill = cat),size = 0.3, alpha = 0.3) +
  scale_fill_manual(values=c("blue","red","yellow","black","white"),name = "Country", labels = c("Business",  "Friends", "Visited","Home", "NA")) +
  #Add a theme to your final map
  theme_void() +
  theme(legend.position = "bottom") + 
  # Add titles to your axis (optional)
  xlab("") +
  ylab("") +
  # Choose the size of your map
  coord_fixed(ratio=1.5, xlim = c(-165,175), ylim = c(-50,78))

```

